@baseUrl = http://localhost:8080

###
# ヘルスチェック
GET {{baseUrl}}

###
# ユーザー作成（新規）
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "name": "新規ユーザー",
  "real_name": "新規太郎",
  "email": "newuser@exafample.com",
  "password": "password123",
  "icon": "https://i.pravatar.cc/150?img=10",
  "profile_memo": "新しく登録したユーザーです"
}

### 全ユーザー取得
GET {{baseUrl}}/api/users


### 特定ユーザーの取得（ID: 3）
GET {{baseUrl}}/api/users/4

###

GET {{baseUrl}}/api/users/search?name=高橋美咲
###
# 特定ユーザーの更新（ID: 1 - 田中太郎）
PUT {{baseUrl}}/api/users/1
Content-Type: application/json

{
  "name": "田中太郎（更新済み）",
  "email": "tanaka_updated@example.com"
}
###
# 特定ユーザーの更新（ID: 2 - 佐藤花子）
PUT {{baseUrl}}/api/users/2
Content-Type: application/json

{
  "name": "佐藤花子（プロフィール更新）",
  "email": "sato_new@example.com"
}

###
# ユーザー削除（ID: 5 - 伊藤健太）
DELETE {{baseUrl}}/api/users/5


###



###
# サブスクリプション作成
POST {{baseUrl}}/api/subscriptions
Content-Type: application/json

{
  "user_id": 1,
  "product_name": "Netflix",
  "category_id": 1,
  "amount": 1490,
  "frequency": "monthly"
}

###
# 全サブスクリプション取得
GET {{baseUrl}}/api/subscriptions

###
# 特定サブスクリプションの更新（ID: 1）
PUT {{baseUrl}}/api/subscriptions/3
Content-Type: application/json

{
  "product_name": "Netflix Premiumfad",
  "amount": 1990,
  "frequency": "monthly"
}

###
# 特定サブスクリプションの削除（ID: 1）
DELETE {{baseUrl}}/api/subscriptions/3


###

GET {{baseUrl}}/api/expenses

###

POST {{baseUrl}}/api/expenses
Content-Type: application/json

{
  "user_id": 1,
  "category_id": 1,
  "amount": 1490,
  "date": "2023-01-01",
  "memo": "Netflix"
}

###
# スクレイピングガイド取得
GET {{baseUrl}}/api/scrape/guide

###
# スクレイピング実行（カスタムセレクタ）
POST {{baseUrl}}/api/scrape
Content-Type: application/json

{
  "url": "https://www.rakuten.co.jp/category/100155/?l-id=top_normal_gmenu_electronics_0",
  "item_selector": ".searchresultitem",
  "name_selector": ".content.title h2 a",
  "price_selector": ".price .important",
  "link_selector": ".content.title h2 a"
}

###
# スクレイピング実行（デフォルトセレクタ）
POST {{baseUrl}}/api/scrape
Content-Type: application/json

{
  "url": "https://www.rakuten.co.jp/category/100155/?l-id=top_normal_gmenu_electronics_0"
}
###
# スクレイピング実行（DB保存あり - 楽天市場）
POST {{baseUrl}}/api/scrape
Content-Type: application/json

{
  "url": "https://www.rakuten.co.jp/category/100155/?l-id=top_normal_gmenu_electronics_0",
  "save": true,
  "website_name": "Rakuten Electronics",
  "item_selector": ".searchresultitem",
  "name_selector": ".content.title h2 a",
  "price_selector": ".price .important",
  "link_selector": ".content.title h2 a"
}
