@baseUrl = http://localhost:8080

### スクレイピングガイド取得
GET {{baseUrl}}/api/scrape/guide

### スクレイピング実行（カスタムセレクタ）
POST {{baseUrl}}/api/scrape
Content-Type: application/json

{
  "url": "https://www.rakuten.co.jp/category/100155/?l-id=top_normal_gmenu_electronics_0",
  "item_selector": ".searchresultitem",
  "name_selector": ".content.title h2 a",
  "price_selector": ".price .important",
  "link_selector": ".content.title h2 a"
}

### スクレイピング実行（デフォルトセレクタ）
POST {{baseUrl}}/api/scrape
Content-Type: application/json

{
  "url": "https://www.rakuten.co.jp/category/100155/?l-id=top_normal_gmenu_electronics_0"
}
### スクレイピング実行（DB保存あり - 楽天市場）
POST {{baseUrl}}/api/scrape
Content-Type: application/json

{
  "url": "https://www.rakuten.co.jp/category/100155/?l-id=top_normal_gmenu_electronics_0",
  "save": true,
  "website_name": "Rakuten Electronics",
  "item_selector": ".searchresultitem",
  "name_selector": ".content.title h2 a",
  "price_selector": ".price .important",
  "link_selector": ".content.title h2 a"
}
